name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install ROS2 tools
      run: |
        sudo apt-get update
        sudo apt install software-properties-common
        sudo add-apt-repository universe
        sudo apt update && sudo apt install curl -y
        export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
        curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
        sudo dpkg -i /tmp/ros2-apt-source.deb
        sudo apt update
        sudo apt upgrade
        sudo apt install ros-humble-desktop
        sudo apt install python3-colcon-common-extensions

    - name: Install Gazebo
      run: |
        sudo apt install ros-humble-ros-ign
        sudo apt install ros-humble-ros-ign-bridge
    - name: build package
      run: source /opt/ros/humble/setup.bash && colcon build --symlink-install --packages-up-to wheeled_model_enhanced
    - name: run
      run: export BUILD_TESTING=ON && cd src/wheeled_model_enhanced/ && mkdir build_tests && cd build_tests && cmake .. && make -j $(nproc) && ./wheeled_model_enhanced_test
